export const types = {
  input: "input",
  select: "select",
  number: "number",
  checkBox: "checkBox",
  radio: "radio",
  date: "date",
  switch: "switch",
  title: "title",
  time: "time",
  slider: "slider",
  rate: "rate",
  color: "color",
  cascader: "cascader",
  area: "area",
};
