export const types = {
  input: "input",
  select: "select",
  number: "number",
  checkBox: "checkBox",
  check: "check",
  radio: "radio",
  date: "date",
  switch: "switch",
  title: "title",
  time: "time",
  slider: "slider",
  rate: "rate",
  color: "color",
  cascader: "cascader",
  table: "table",
  editor: "editor",
};
